export const INIT_PROGRAMS = 'INIT_PROGRAMS';
export const FILTER_BY_YEAR = 'FILTER_BY_YEAR';
export const FILTER_BY_SUCCESSFUL_LAUNCH = 'FILTER_BY_SUCCESSFUL_LAUNCH';
export const FILTER_BY_SUCCESSFUL_LANDING = 'FILTER_BY_SUCCESSFUL_LANDING';