export const INIT_PROGRAMS = 'INIT_PROGRAMS';
export const INIT_PROGRAMS_START = 'INIT_PROGRAMS_START';
export const INIT_PROGRAMS_SUCCESS = 'INIT_PROGRAMS_SUCCESS';
export const INIT_PROGRAMS_FAILURE = 'INIT_PROGRAMS_FAILURE';
export const FILTER_BY_YEAR = 'FILTER_BY_YEAR';
export const FILTER_BY_SUCCESSFUL_LAUNCH = 'FILTER_BY_SUCCESSFUL_LAUNCH';
export const FILTER_BY_SUCCESSFUL_LANDING = 'FILTER_BY_SUCCESSFUL_LANDING';